#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _object_relpath(compile_source: Path, workspace_root: Path) -> Path:
    rel_path = compile_source.resolve().relative_to(workspace_root.resolve())
    if compile_source.suffix == ".c":
        return rel_path.with_suffix(".rel")
    if compile_source.suffix == ".asm":
        return rel_path.with_suffix(".rel")
    raise ValueError(f"Unsupported compile source type: {compile_source}")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def generate_native_plan(
    compile_plan: list[dict[str, Any]],
    *,
    workspace_root: Path,
    obj_dir: Path,
    entries_dir: Path,
) -> tuple[list[dict[str, str]], list[str]]:
    entries: list[dict[str, str]] = []
    skipped: list[str] = []
    for index, item in enumerate(compile_plan):
        if item.get("skip"):
            skipped.append(str(item.get("compile_source", item.get("source", f"entry-{index}"))))
            continue

        error = item.get("error")
        if isinstance(error, str) and error:
            raise SystemExit(error)

        compile_source_value = item.get("compile_source")
        if not isinstance(compile_source_value, str):
            raise SystemExit(f"compile_plan[{index}] missing compile_source")

        compile_source = Path(compile_source_value)
        object_path = obj_dir / _object_relpath(compile_source, workspace_root)
        entry_path = entries_dir / f"{index:03d}.json"
        _write_json(entry_path, item)
        entries.append(
            {
                "entry_file": str(entry_path),
                "object_file": str(object_path),
                "compile_source": str(compile_source),
            }
        )
    return entries, skipped


def write_cmake_fragment(path: Path, entries: list[dict[str, str]], skipped: list[str]) -> None:
    lines = [
        "# Auto-generated by Tools/sdcc/gen_native_cmake_plan.py",
        "set(ZSTACK_NATIVE_OBJECTS",
    ]
    for entry in entries:
        lines.append(f'  "{entry["object_file"]}"')
    lines.append(")")
    lines.append("set(ZSTACK_NATIVE_ENTRY_FILES")
    for entry in entries:
        lines.append(f'  "{entry["entry_file"]}"')
    lines.append(")")
    lines.append("set(ZSTACK_NATIVE_COMPILE_SOURCES")
    for entry in entries:
        lines.append(f'  "{entry["compile_source"]}"')
    lines.append(")")
    lines.append("set(ZSTACK_NATIVE_SKIPPED_SOURCES")
    for source in skipped:
        lines.append(f'  "{source}"')
    lines.append(")")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a native CMake compile plan from SDCC compile-plan.json")
    parser.add_argument("--compile-plan", required=True, type=Path)
    parser.add_argument("--workspace-root", required=True, type=Path)
    parser.add_argument("--obj-dir", required=True, type=Path)
    parser.add_argument("--entries-dir", required=True, type=Path)
    parser.add_argument("--cmake-out", required=True, type=Path)
    args = parser.parse_args()

    compile_plan = json.loads(args.compile_plan.read_text(encoding="utf-8"))
    entries, skipped = generate_native_plan(
        compile_plan,
        workspace_root=args.workspace_root,
        obj_dir=args.obj_dir,
        entries_dir=args.entries_dir,
    )
    write_cmake_fragment(args.cmake_out, entries, skipped)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
