#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any

if __package__ in (None, ""):
    PACKAGE_ROOT = Path(__file__).resolve().parent
    if str(PACKAGE_ROOT) not in sys.path:
        sys.path.insert(0, str(PACKAGE_ROOT))

    from extract_iar_project import collect_manifest, write_sdcc_header
    from gen_compile_plan import build_compile_plan
    from sdcc_contract import merge_sdcc_extra_sources, sdcc_flash_reservation_sources, sdcc_required_areas, sdcc_sleep_entry_sources
else:
    from .extract_iar_project import collect_manifest, write_sdcc_header
    from .gen_compile_plan import build_compile_plan
    from .sdcc_contract import merge_sdcc_extra_sources, sdcc_flash_reservation_sources, sdcc_required_areas, sdcc_sleep_entry_sources


PORTING_DOC = Path(__file__).resolve().with_name("SDCC_PORTING.md")


def _sanitize_target_name(value: str) -> str:
    lowered = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip()).strip("_").lower()
    return lowered or "zstack_project"


def _write_json(path: Path, payload: dict[str, Any] | list[Any]) -> None:
    _write_text_if_changed(path, json.dumps(payload, indent=2) + "\n")


def _write_text_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8", errors="ignore") == content:
        return
    path.write_text(content, encoding="utf-8")


def _copy_file_if_changed(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and dst.read_bytes() == src.read_bytes():
        return
    shutil.copyfile(src, dst)


def _project_service_root(*, out_dir: Path, profile: str, write_cmakelists: Path | None) -> Path:
    if write_cmakelists is not None:
        return write_cmakelists.resolve().parent

    resolved_out_dir = out_dir.resolve()
    if resolved_out_dir.name == profile and resolved_out_dir.parent.name == ".sdcc-import":
        return resolved_out_dir.parent.parent
    return resolved_out_dir.parent


def _copy_porting_doc(project_root: Path) -> None:
    if not PORTING_DOC.exists():
        raise FileNotFoundError(f"Missing SDCC porting guide: {PORTING_DOC}")

    _copy_file_if_changed(PORTING_DOC, project_root / PORTING_DOC.name)


def _write_import_project_cmake(
    path: Path,
    *,
    project_name: str,
    profile: str,
    import_root: Path,
    manifest_path: Path,
    compile_plan_path: Path,
    cfg_header_path: Path,
    source_files: list[str],
) -> None:
    configure_depends = [path.as_posix(), manifest_path.as_posix(), compile_plan_path.as_posix(), cfg_header_path.as_posix()]
    source_file_lines = "\n".join(f'  "{source}"' for source in source_files)
    content = f"""# Auto-generated by Tools/sdcc/import_external_iar_project.py
set(ZSTACK_IMPORTED_PROFILE "{profile}")
set(ZSTACK_IMPORTED_PROJECT_NAME "{project_name}")
set(ZSTACK_IMPORTED_IMPORT_ROOT "{import_root.as_posix()}")
set(ZSTACK_IMPORTED_METADATA_DIR "{(import_root / "metadata").as_posix()}")
set(ZSTACK_IMPORTED_INCLUDE_ROOT "{(import_root / "include").as_posix()}")
set(ZSTACK_IMPORTED_MANIFEST "{manifest_path.as_posix()}")
set(ZSTACK_IMPORTED_COMPILE_PLAN "{compile_plan_path.as_posix()}")
set(ZSTACK_IMPORTED_GENERATED_CFG_HEADER "{cfg_header_path.as_posix()}")
set(ZSTACK_IMPORTED_CONFIGURE_DEPENDS
  "{configure_depends[0]}"
  "{configure_depends[1]}"
  "{configure_depends[2]}"
  "{configure_depends[3]}"
)
set(ZSTACK_IMPORTED_SOURCE_FILES
{source_file_lines}
)
set(ZSTACK_IMPORTED_SDCC_MODEL "large")
set(ZSTACK_IMPORTED_SDCC_ABI "iar")
set(ZSTACK_IMPORTED_SDCC_STACK_MODE "default")
set(ZSTACK_IMPORTED_SDCC_CODE_LOC "0x0000")
set(ZSTACK_IMPORTED_SDCC_CODE_SIZE "")
set(ZSTACK_IMPORTED_SDCC_XRAM_LOC "0x0001")
set(ZSTACK_IMPORTED_SDCC_XRAM_SIZE "0x1EFF")
set(ZSTACK_IMPORTED_SDCC_XSTACK_LOC "")
"""
    _write_text_if_changed(path, content)


def _relative_to_project(path: Path, project_root: Path) -> str:
    try:
        return path.resolve().relative_to(project_root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _write_top_level_cmake(
    path: Path,
    *,
    project_file: Path,
    config: str,
    profile: str,
    target_name: str,
) -> None:
    project_root = path.parent.resolve()
    project_rel = _relative_to_project(project_file, project_root)
    content = f"""cmake_minimum_required(VERSION 3.20)

project({target_name}_sdcc NONE)

set(ZSTACK_ROOT "" CACHE PATH "Path to the Z-Stack SDK root containing Components/ and Projects/.")
set(SDCC_TOOLCHAIN_ROOT "" CACHE PATH "Path to the prepared SDCC toolchain root.")
set(ZSTACK_PROFILE "{profile}" CACHE STRING "External Z-Stack SDCC import profile.")
set(ZSTACK_SDCC_CMAKE_MODULE "" CACHE FILEPATH "Optional override for ZStackSDCC.cmake.")
set(ZSTACK_OUTPUT_BASE_DIR "${{CMAKE_BINARY_DIR}}/out/{target_name}" CACHE PATH "Base output directory for firmware artifacts.")
set(SDCC_PORT_INCLUDE_DIR "" CACHE PATH "Optional SDCC mcs51 include directory override.")

if(NOT ZSTACK_ROOT)
  message(FATAL_ERROR "Set ZSTACK_ROOT to the Z-Stack SDK root before configuring.")
endif()
if(NOT SDCC_TOOLCHAIN_ROOT)
  message(FATAL_ERROR "Set SDCC_TOOLCHAIN_ROOT before configuring.")
endif()

if(NOT ZSTACK_SDCC_CMAKE_MODULE)
  set(ZSTACK_SDCC_CMAKE_MODULE "${{ZSTACK_ROOT}}/../cmake/ZStackSDCC.cmake")
endif()
if(NOT EXISTS "${{ZSTACK_SDCC_CMAKE_MODULE}}")
  message(FATAL_ERROR "Cannot find ZStackSDCC.cmake. Set ZSTACK_SDCC_CMAKE_MODULE explicitly.")
endif()
if(NOT SDCC_PORT_INCLUDE_DIR AND EXISTS "${{ZSTACK_ROOT}}/../../sdcc/device/include/mcs51")
  set(SDCC_PORT_INCLUDE_DIR "${{ZSTACK_ROOT}}/../../sdcc/device/include/mcs51")
endif()

find_package(Python3 REQUIRED COMPONENTS Interpreter)
include("${{ZSTACK_SDCC_CMAKE_MODULE}}")

zstack_add_external_iar_project_target(
  NAME {target_name}
  PROJECT_FILE "${{CMAKE_CURRENT_SOURCE_DIR}}/{project_rel}"
  CONFIG "{config}"
  PROFILE "${{ZSTACK_PROFILE}}"
  SOURCE_ROOT "${{CMAKE_CURRENT_SOURCE_DIR}}"
  ZSTACK_ROOT "${{ZSTACK_ROOT}}"
  TOOLCHAIN_ROOT "${{SDCC_TOOLCHAIN_ROOT}}"
  PORT_INCLUDE_DIR "${{SDCC_PORT_INCLUDE_DIR}}"
  WORK_ROOT "${{CMAKE_BINARY_DIR}}/work"
  IMPORT_DIR "${{CMAKE_CURRENT_SOURCE_DIR}}/.sdcc-import/${{ZSTACK_PROFILE}}"
  OUTPUT_BASE_DIR "${{ZSTACK_OUTPUT_BASE_DIR}}"
  PYTHON_EXECUTABLE "${{Python3_EXECUTABLE}}"
)

message(STATUS "External Z-Stack project: {target_name}")
message(STATUS "Firmware artifacts: ${{ZSTACK_OUTPUT_BASE_DIR}}/${{ZSTACK_PROFILE}}")
"""
    _write_text_if_changed(path, content)


def import_external_project(args: argparse.Namespace) -> None:
    project_file = args.project.resolve()
    zstack_root = args.zstack_root.resolve()
    out_dir = args.out_dir.resolve()
    target_name = _sanitize_target_name(args.target_name or f"{project_file.stem}_{args.config}")
    project_name = f"{project_file.stem}-{args.config}"

    metadata_dir = out_dir / "metadata"
    include_dir = out_dir / "include"
    cmake_dir = out_dir / "cmake"
    manifest_path = metadata_dir / "manifest.json"
    compile_plan_path = out_dir / "compile-plan.json"
    cfg_header_path = include_dir / f"{target_name}-sdcc-cfg.h"
    project_cmake_path = cmake_dir / "project.cmake"
    report_path = out_dir / "report.json"

    manifest = collect_manifest(project_file, args.config, repo_root=zstack_root)
    manifest["profile"] = args.profile
    manifest["sdcc_required_areas"] = sdcc_required_areas(args.profile)
    manifest["sdcc_extra_sources"] = merge_sdcc_extra_sources(
        manifest.get("sdcc_extra_sources", []),
        [
            *sdcc_sleep_entry_sources(),
            *sdcc_flash_reservation_sources(args.profile),
        ],
    )
    manifest["import_sidecar_root"] = str(out_dir)
    manifest["sdcc_generated_cfg_header"] = str(cfg_header_path)
    manifest["generated_include_dirs"] = [str(include_dir)]

    write_sdcc_header(cfg_header_path, manifest["sdcc_header_defines"])
    _write_json(manifest_path, manifest)

    compile_plan = build_compile_plan(manifest)
    _write_json(compile_plan_path, compile_plan)

    _write_import_project_cmake(
        project_cmake_path,
        project_name=project_name,
        profile=args.profile,
        import_root=out_dir,
        manifest_path=manifest_path,
        compile_plan_path=compile_plan_path,
        cfg_header_path=cfg_header_path,
        source_files=[str(source) for source in manifest.get("source_files", []) if isinstance(source, str)],
    )

    _write_json(
        report_path,
        {
            "target_name": target_name,
            "project_name": project_name,
            "configuration": args.config,
            "profile": args.profile,
            "project_file": str(project_file),
            "zstack_root": str(zstack_root),
            "source_files": len(manifest.get("source_files", [])),
            "include_dirs": len(manifest.get("include_dirs", [])),
            "iar_libraries": len(manifest.get("iar_libraries", [])),
        },
    )

    if args.write_cmakelists:
        _write_top_level_cmake(
            args.write_cmakelists.resolve(),
            project_file=project_file,
            config=args.config,
            profile=args.profile,
            target_name=target_name,
        )

    project_root = _project_service_root(
        out_dir=out_dir,
        profile=args.profile,
        write_cmakelists=args.write_cmakelists,
    )
    _copy_porting_doc(project_root)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate in-place CMake sidecar files for an external IAR Z-Stack project.")
    parser.add_argument("--project", required=True, type=Path, help="Path to the external IAR .ewp project file")
    parser.add_argument("--config", required=True, help="IAR configuration name")
    parser.add_argument("--profile", default="full", help="Import profile name used by CMake output paths")
    parser.add_argument("--zstack-root", required=True, type=Path, help="Path to the Z-Stack SDK root")
    parser.add_argument("--out-dir", required=True, type=Path, help="Sidecar import directory, usually .sdcc-import/<profile>")
    parser.add_argument("--target-name", help="CMake target name to generate")
    parser.add_argument("--write-cmakelists", type=Path, help="Optional top-level CMakeLists.txt path to write")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    import_external_project(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
